name: Keep Supabase Active

on:
  schedule:
    # Exécuter tous les jours à 05:00 UTC (07:00 en France en été, 06:00 en hiver)
    - cron: '0 5 * * *'
  workflow_dispatch: # Permet de lancer le ping manuellement depuis l'onglet Actions de GitHub

jobs:
  keep-alive:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Supabase REST API
        run: |
          curl -i -X GET \
            -H "apikey: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9nbGRsempmamlscGF2YXpiaW5pIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzg1MTc1MzYsImV4cCI6MjA5NDA5MzUzNn0.p96F0nQbzNZys4cS9TaQ2TAo3j6O7DoeoqVCLTRDkpI" \
            "https://ogldlzjfjilpavazbini.supabase.co/rest/v1/finds?limit=1"
